/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 05 07:36:34 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl2.Book;
import ir.ramtung.impl2.Magazine;
import ir.ramtung.impl2.Student;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Student_ESTest extends Student_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Student student0 = new Student("UKV", "ir.ramtung.impl2.Student");
      Book book0 = new Book("ir.ramtung.impl2.Student", 1);
      student0.borrow(book0);
      assertTrue(student0.canBorrow());
      
      Magazine magazine0 = new Magazine("UKV", (-1653), 1, (-1));
      student0.borrow(magazine0);
      student0.borrow(book0);
      boolean boolean0 = student0.canBorrow();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Student student0 = new Student("", "]E>D|*8R`uWR^yCwM_");
      student0.docsBorrow = null;
      // Undeclared exception!
      try { 
        student0.canBorrow();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ir.ramtung.impl2.Student", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Student student0 = new Student("UKV", "ir.ramtung.impl2.Student");
      boolean boolean0 = student0.canBorrow();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Student student0 = new Student("UKV", "ir.ramtung.impl2.Student");
      Book book0 = new Book("ir.ramtung.impl2.Student", 1);
      student0.borrow(book0);
      assertTrue(student0.canBorrow());
      
      Magazine magazine0 = new Magazine("UKV", (-1653), 1, (-1));
      student0.borrow(magazine0);
      boolean boolean0 = student0.canBorrow();
      assertFalse(boolean0);
  }
}
