/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 05 07:33:21 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Magazine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("mpT+!mnrcxr", 1390, 477);
      int int0 = magazine0.penaltyFor((-1));
      assertEquals((-3000), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine("Documents with empty title are not allowed", 1, 1);
      int int0 = magazine0.penaltyFor(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = new Magazine("<a%", 1106, 1106);
      int int0 = magazine0.penaltyFor(1106);
      assertEquals(2212000, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Magazine magazine0 = new Magazine("<a%", 1106, 1106);
      magazine0.year = 2212000;
      int int0 = magazine0.penaltyFor(2212000);
      assertEquals((-1953934592), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("ir.rmun.impl1.InBldArgumentE", 3003, (-98));
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative number
         //
         verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine((String) null, (-987), (-987));
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative publication year
         //
         verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Magazine magazine0 = new Magazine("<a%", 1106, 1106);
      int int0 = magazine0.loanDuration();
      assertEquals(2, int0);
  }
}
