/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 05 07:38:06 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Magazine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("C&4|Y `!*T\"{dL2qi,m", 1390, 1390, 1390);
      int int0 = magazine0.calculatePenalty(1390);
      assertEquals(2, magazine0.getDay());
      assertEquals(3000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine("84(`%T(", 163, 163, 163);
      int int0 = magazine0.calculatePenalty(163);
      assertEquals(2000, int0);
      assertEquals(2, magazine0.getDay());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = new Magazine("84(`%T(", 163, 163, 163);
      magazine0.year = 2000;
      int int0 = magazine0.calculatePenalty(2000);
      assertEquals(2, magazine0.getDay());
      assertEquals(3000, int0);
  }
}
